### ISSUE TITLE
querystring query using field names in searchbox to query data

### ISSUE THREAD

**Issue by fedenolasco** [svola/ElasticUI-extension#4]
I am new to ElasticUI-extension, but I managed to set it up successfully. It's working well.

Now I want to achieve the following in my search box;

Let's say I have documents indexed with various date fields; field1date, field2date, field3date.

I now it is possible to query a specific field through the searchbox as **fieldname:value**, let's say dateofbirth:1970-06-13?

How can I achieve this in the searchbox from the ElasticUI-extension? It may require some coding I guess?

Thanks, Fede.

**Comment by svola** [comment]
Query String Query should just work out of the box:

https://github.com/svola/ElasticUI-extension/blob/master/materializecss-template/demo.html#L39

https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-query-string-query.html#query-string-syntax

For the supported date-formats please refer to:
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping-date-format.html#built-in

So this will basically depend on how you index your data. If the required date format is not built in, you might have to use a custom date format pattern:

http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html

**Comment by fedenolasco** [comment]
That worked just fine. I think the link 
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-query-string-query.html#query-string-syntax was very self-explanotory.

Fede,
